[build]
  command = "npm install --legacy-peer-deps && npm run build --legacy-peer-deps"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18.20.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
